_target_: src.models.grassy_module.GrassyModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  input_dim: int
  hidden_dim_autoencoder: int
  latent_dim: int
  hidden_dim_property_predictor: int
  property_dim: 3
  alpha: 0.1

# compile model for faster training with pytorch 2.0
compile: false

