_target_: src.models.grassy_module.GrassyModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  input_dim: 74 # number of unique atom types
  hidden_dim_autoencoder: 512
  latent_dim: 256
  hidden_dim_property_predictor: 128
  property_dim: 5 # number of molecular properties to predict
  alpha: 0.1